In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import math
from datetime import datetime,timedelta
import re

In [2]:
kdd_root = '/home/chenhr/Documents/KDD2017/dataSets/dataSets/training/'
volume_data = 'volume(table 6)_training.csv'
weather_data = 'weather (table 7)_training_update.csv'

In [3]:
volume_raw_training_data = pd.read_csv(kdd_root+volume_data)
volume_raw_training_data.head()

,time,tollgate_id,direction,vehicle_model,has_etc,vehicle_type
0,2016-09-19 23:09:25,2,0,1,0,NaN
1,2016-09-19 23:11:53,2,0,1,0,NaN
2,2016-09-19 23:13:54,2,0,1,0,NaN
3,2016-09-19 23:17:48,1,0,1,1,NaN
4,2016-09-19 23:16:07,2,0,1,0,NaN

In [4]:
#reform the date
def reform_date(date):
    _date_ = re.split('\/',date)
    if len(_date_[1])==1:
        _date_[1]='0'+_date_[1]
    if len(_date_[2])==1:
        _date_[2]='0'+_date_[2]
        
    return _date_[0]+'-'+_date_[1]+'-'+_date_[2]

In [5]:
weather_raw_data = pd.read_csv(kdd_root+weather_data)
weather_raw_data['date']=weather_raw_data['date'].apply(reform_date)

weather_raw_data.head()

,date,hour,pressure,sea_pressure,wind_direction,wind_speed,temperature,rel_humidity,precipitation
0,2016-07-01,0,1000.4,1005.3,225.0,2.1,26.4,94.0,0.0
1,2016-07-01,3,1000.5,1005.3,187.0,2.7,29.0,76.0,0.0
2,2016-07-01,6,998.9,1003.7,212.0,2.9,31.7,67.0,0.0
3,2016-07-01,9,998.7,1003.5,244.0,2.7,31.6,59.0,0.0
4,2016-07-01,12,999.7,1004.5,222.0,1.3,29.9,68.0,0.0

In [6]:
volume_raw_training_data['vehicle_type'] = volume_raw_training_data['vehicle_type'].fillna(2)
volume_raw_training_data.head()

,time,tollgate_id,direction,vehicle_model,has_etc,vehicle_type
0,2016-09-19 23:09:25,2,0,1,0,2.0
1,2016-09-19 23:11:53,2,0,1,0,2.0
2,2016-09-19 23:13:54,2,0,1,0,2.0
3,2016-09-19 23:17:48,1,0,1,1,2.0
4,2016-09-19 23:16:07,2,0,1,0,2.0

In [6]:
#do some experiment

from datetime import datetime,timedelta
volume_raw_training_data.iat[0,0]
time = datetime.strptime(volume_raw_training_data.iat[0,0],"%Y-%m-%d %H:%M:%S")
str(time)

'2016-09-19 23:09:25'

In [7]:
#Creat time window
def get_time_window(time):
    time = datetime.strptime(time,"%Y-%m-%d %H:%M:%S")
    time_window_minute = int(math.floor(time.minute/20)*20)
    time_window_start = datetime(time.year,time.month,time.day,time.hour,
                                 time_window_minute,0)
    time_window_end = time_window_start + timedelta(minutes=20)
    time_window ='[' + str(time_window_start) + ',' + str(time_window_end) +")"
    return time_window

In [8]:
#Creat time hour
def get_time_hour(time):
    time = datetime.strptime(time,"%Y-%m-%d %H:%M:%S")
    time_hour = int(math.floor(time.hour/3)*3)
    return time_hour

In [9]:
volume_raw_training_data['time_window'] = volume_raw_training_data['time'].apply(get_time_window)
volume_raw_training_data['time_hour'] = volume_raw_training_data['time'].apply(get_time_hour)

In [12]:
volume_raw_training_data.shape

(543699, 8)

In [11]:
time_window_set = set(volume_raw_training_data.time_window.values)
ID = [1,2,3]
DIRECTION =[0,1]
len(time_window_set)

2088

In [100]:
#do some experiment

a = pd.value_counts(volume_raw_training_data.vehicle_model==1)


print a

True     391622
False    152077
Name: vehicle_model, dtype: int64

In [13]:
volume_data_columns = ['time_window','tollgate_id','direction','vehicle_model0',
                       'vehicle_model1','vehicle_model2','vehicle_model3',
                       'vehicle_model4','vehicle_model5','vehicle_model6',
                       'has_etc','no_etc','vehicle_type0','vehicle_type1',
                       'vehicle_type2','pressure','sea_pressure','wind_direction',
                       'wind_speed','temperature','rel_humidity','precipitation',
                       'weekday','date','hour','volumes']
volume_collected_training_data = pd.DataFrame(columns=[volume_data_columns])
#print volume_collected_training_data

In [41]:
#do some experiment

np.full((0,4),np.nan)
aa = pd.Series(np.nan,index=volume_data_columns)
#print aa

weather_series = weather_raw_data[(weather_raw_data['date']=='2016-10-04')&(weather_raw_data['hour']==0)]
sss = pd.Series(np.nan,index=volume_data_columns)
print weather_series
weather_series.iloc[0,2]

           date  hour  pressure  sea_pressure  wind_direction  wind_speed  \
758  2016-10-04     0    1008.0        1013.0           330.0         2.3

     temperature  rel_humidity  precipitation
758         21.6          84.0            0.0

1008.0

In [162]:
#do some experiment

volume_raw_training_data[volume_raw_training_data.time_window== '[2016-09-19 23:00:00,2016-09-19 23:20:00)']

aaa =[]
len(aaa)

0

In [139]:
#do some experiment

date_ = '[2016-09-1 23:00:00,2016-09-19 23:20:00)'
time_ = datetime.strptime(re.split('\[|\ |\,|\)',date_)[2],'%H:%M:%S')
#re.split('\[|\ |\,|\)',date_)
#re.split('\-','2016-09-1')
#month_,date_ = [re.split('\-','2016-09-1')[1],re.split('\-','2016-09-1')[2]]
#print month_
#print date_
temp_weather = weather_raw_data[(weather_raw_data['date']=='2016-10-04')
                                    &(weather_raw_data['hour']==0)]
temp_weather
np.arange(0,371.25,22.5)

array([   0. ,   22.5,   45. ,   67.5,   90. ,  112.5,  135. ,  157.5,
        180. ,  202.5,  225. ,  247.5,  270. ,  292.5,  315. ,  337.5,
        360. ])

In [14]:
def get_wd(wind_direction):
    wd_ =np.arange(0,371.25,22.5)
    if wind_direction != 999017:
        temp_list = [math.fabs(wind_direction-wd) for wd in wd_]
        wd_index = temp_list.index(min(temp_list))
    else:
        return 'no_direction' 
    
    switcher ={0:'N',1:'NNE',2:'NE',3:'ENE',4:'E',5:'ESE',6:'SE',7:'SSE',8:'S',9:'SSW',
               10:'SW',11:'WSW',12:'W',13:'WNW',14:'NW',15:'NNW',16:'N'}
    return switcher.get(wd_index,'no_direction')

array([   0. ,   22.5,   45. ,   67.5,   90. ,  112.5,  135. ,  157.5,
        180. ,  202.5,  225. ,  247.5,  270. ,  292.5,  315. ,  337.5,
        360. ])

In [15]:
for _time_window_set_ in time_window_set:
    time_window_data = volume_raw_training_data[volume_raw_training_data.time_window
                                               == _time_window_set_]
    _date_ = re.split('\[|\ |\,|\)',_time_window_set_)[1]
    get_time = re.split('\[|\ |\,|\)',_time_window_set_)[2]
    time_ = datetime.strptime(get_time,'%H:%M:%S')
    hour_ = int(math.floor(time_.hour/3)*3)
    #month_,date_ = [re.split('\-',_date_)[1],re.split('\-',_date_)[2]]
    time_window_ = '[' + re.split('\[|\ |\,|\)',_time_window_set_)[2] + ','+re.split('\[|\ |\,|\)',_time_window_set_)[4]+')'
    weekday_ = datetime.strptime(_date_,'%Y-%m-%d').weekday()
    temp_weather = weather_raw_data[(weather_raw_data['date']==_date_)
                                    &(weather_raw_data['hour']==hour_)]
   
    for _id in ID:
        for _direction in DIRECTION:
            if _id==2 and _direction==1:
                continue
            
            temp_s = pd.Series(np.nan,index=volume_data_columns)
            
            temp_time_window_data = time_window_data[(time_window_data.tollgate_id == _id)
                                                     &(time_window_data.direction == _direction)]
            temp_s['time_window'] = time_window_
            temp_s['tollgate_id'] = _id
            temp_s['direction'] = _direction
            temp_s['vehicle_model0'] = int(list(temp_time_window_data['vehicle_model']).count(0))
            temp_s['vehicle_model1'] = int(list(temp_time_window_data['vehicle_model']).count(1))
            temp_s['vehicle_model2'] = int(list(temp_time_window_data['vehicle_model']).count(2))
            temp_s['vehicle_model3'] = int(list(temp_time_window_data['vehicle_model']).count(3))
            temp_s['vehicle_model4'] = int(list(temp_time_window_data['vehicle_model']).count(4))
            temp_s['vehicle_model5'] = int(list(temp_time_window_data['vehicle_model']).count(5))
            temp_s['vehicle_model6'] = int(list(temp_time_window_data['vehicle_model']).count(6))
            temp_s['has_etc'] = int(list(temp_time_window_data['has_etc']).count(1))
            temp_s['no_etc'] = int(list(temp_time_window_data['has_etc']).count(0))
            temp_s['vehicle_type0'] = int(list(temp_time_window_data['vehicle_type']).count(0))
            temp_s['vehicle_type1'] = int(list(temp_time_window_data['vehicle_type']).count(1))
            temp_s['vehicle_type2'] = int(list(temp_time_window_data['vehicle_type']).count(2))
            temp_s['pressure'] = temp_weather.iloc[0,2]
            temp_s['sea_pressure'] = temp_weather.iloc[0,3]
            temp_s['wind_direction'] = get_wd(temp_weather.iloc[0,4])
            temp_s['wind_speed'] = temp_weather.iloc[0,5]
            temp_s['temperature'] = temp_weather.iloc[0,6]
            temp_s['rel_humidity'] = temp_weather.iloc[0,7]
            temp_s['precipitation'] = temp_weather.iloc[0,8]
            temp_s['weekday'] = weekday_
            temp_s['date'] = _date_
            temp_s['hour'] = hour_
            temp_s['volumes'] = len(temp_time_window_data)
            volume_collected_training_data = volume_collected_training_data.append(temp_s,ignore_index=True)

In [19]:
volume_collected_training_data.wind_direction.value_counts()
#volume_collected_training_data.shape

N               1890
NNW             1620
NE              1485
E               1170
NW               945
NNE              855
ENE              765
ESE              405
SW               405
WNW              270
SSW              180
S                180
no_direction      90
SSE               45
W                 45
WSW               45
SE                45
Name: wind_direction, dtype: int64

In [20]:
list(volume_collected_training_data.wind_direction).count('no_direction')

90

In [21]:
#redifine time window
def count_time(time_window):
    time_ = datetime.strptime(re.split('\[|\ |\,|\)',time_window)[1],'%H:%M:%S')
    return int((time_.hour*3 )+ (time_.minute/20))
    
    
volume_collected_training_data['time_window_'] = volume_collected_training_data['time_window'].apply(count_time)

In [22]:
#redifine date
volume_collected_training_data['date'] = volume_collected_training_data['date'].apply(lambda x: int(re.split('\-',x)[2]))

In [23]:
#redifine wind_direction
def redifine_wd(wind_direction):
    switcher ={
        'N':0,
        'NNE':1,
        'NE':2,
        'ENE':3,
        'E':4,
        'ESE':5,
        'SE':6,
        'SSE':7,
        'S':8,
        'SSW':9,
        'SW':10,
        'WSW':11,
        'W':12,
        'WNW':13,
        'NW':14,
        'NNW':15,
        'N':16,
        'no_direction':17,
    }
    return switcher.get(wind_direction)
volume_collected_training_data['wind_direction'] = volume_collected_training_data['wind_direction'].apply(redifine_wd)

In [33]:
volume_collected_training_data.shape

(10440, 27)

In [25]:
#drop some variable
volume_droped =volume_collected_training_data.drop(['sea_pressure','pressure','hour','time_window',],axis=1,inplace=False)

### One-Hot Coding

In [26]:
var_to_encode = ['tollgate_id','direction','wind_direction']

volume_droped = pd.get_dummies(volume_droped, columns=var_to_encode)

In [34]:
volume_droped.shape

(10440, 42)

In [29]:
list_ = ['time_window_','date','weekday','tollgate_id_1',
       'tollgate_id_2','tollgate_id_3','direction_0','direction_1',
      'vehicle_model0','vehicle_model1','vehicle_model2','vehicle_model3',
       'vehicle_model4','vehicle_model5','vehicle_model6','has_etc','no_etc',
      'vehicle_type0','vehicle_type1','vehicle_type2','temperature','rel_humidity',
       'precipitation','wind_speed',
       'wind_direction_1','wind_direction_2','wind_direction_3','wind_direction_4',
       'wind_direction_5','wind_direction_6','wind_direction_7','wind_direction_8',
       'wind_direction_9','wind_direction_10','wind_direction_11','wind_direction_12',
       'wind_direction_13','wind_direction_14','wind_direction_15','wind_direction_16',
       'wind_direction_17','volumes']

In [30]:
volume_final_train_data = volume_droped[list_]

In [31]:
volume_final_train_data_wo_festival = volume_final_train_data[((18<volume_final_train_data['date'])& (volume_final_train_data['date']<30))|((18>volume_final_train_data['date'])&(volume_final_train_data['date']>7))]

In [32]:
volume_final_train_data_wo_festival.to_csv(kdd_root + 'train_data/train_wo_modified.csv',index=False)

In [38]:
volume_final_train_data_wo_festival.shape

(7560, 42)

In [45]:
from sklearn.ensemble import GradientBoostingClassifier

ImportError: No module named sklearn.ensemble

In [39]:
import scipy

In [46]:
import sklearn

In [86]:
weather_raw_data11 = pd.read_csv(kdd_root+weather_data)
#weather_raw_data11.date

In [93]:
weather_raw_data11['time_window'] = pd.to_datetime(weather_raw_data11.apply(lambda x:'{} {:02}'.format(x.date,x.hour),axis=1))
weather_raw_data11.set_index('time_window',inplace = True)
weather_raw_data11

,date,hour,pressure,sea_pressure,wind_direction,wind_speed,temperature,rel_humidity,precipitation
time_window,,,,,,,,,
2016-07-01 00:00:00,2016/7/1,0,1000.4,1005.3,225.0,2.1,26.4,94.0,0.0
2016-07-01 03:00:00,2016/7/1,3,1000.5,1005.3,187.0,2.7,29.0,76.0,0.0
2016-07-01 06:00:00,2016/7/1,6,998.9,1003.7,212.0,2.9,31.7,67.0,0.0
2016-07-01 09:00:00,2016/7/1,9,998.7,1003.5,244.0,2.7,31.6,59.0,0.0
2016-07-01 12:00:00,2016/7/1,12,999.7,1004.5,222.0,1.3,29.9,68.0,0.0
2016-07-01 15:00:00,2016/7/1,15,1000.0,1004.8,102.0,1.6,27.8,82.0,0.0
2016-07-01 18:00:00,2016/7/1,18,998.8,1003.6,202.0,1.9,26.0,89.0,0.0
2016-07-01 21:00:00,2016/7/1,21,1000.2,1005.0,334.0,2.2,25.5,90.0,0.0
2016-07-02 00:00:00,2016/7/2,0,1001.6,1006.4,315.0,1.8,26.8,82.0,0.0
2016-07-02 03:00:00,2016/7/2,3,1002.4,1007.2,46.0,3.2,30.0,70.0,0.0
2016-07-02 06:00:00,2016/7/2,6,1001.3,1006.2,37.0,2.2,29.3,80.0,1.0
2016-07-02 09:00:00,2016/7/2,9,1001.9,1006.8,345.0,2.4,25.9,95.0,10.2
2016-07-02 12:00:00,2016/7/2,12,1003.6,1008.5,113.0,1.0,25.1,94.0,0.2
2016-07-02 15:00:00,2016/7/2,15,1002.4,1007.3,138.0,1.0,25.3,96.0,0.0
2016-07-02 18:00:00,2016/7/2,18,1000.9,1005.8,221.0,0.7,25.4,96.0,0.0
2016-07-02 21:00:00,2016/7/2,21,1000.9,1005.8,999017.0,0.1,25.2,98.0,0.0
2016-07-03 00:00:00,2016/7/3,0,1001.5,1006.4,220.0,1.5,25.8,97.0,0.0
2016-07-03 03:00:00,2016/7/3,3,1001.5,1006.4,200.0,1.6,27.0,93.0,0.1
2016-07-03 06:00:00,2016/7/3,6,1000.8,1005.7,207.0,1.8,27.4,92.0,0.0
2016-07-03 09:00:00,2016/7/3,9,1000.8,1005.7,223.0,1.1,27.7,91.0,0.1
2016-07-03 12:00:00,2016/7/3,12,1001.6,1006.5,137.0,0.6,26.9,91.0,0.0
2016-07-03 15:00:00,2016/7/3,15,1002.2,1007.1,173.0,0.4,26.0,96.0,0.1
2016-07-03 18:00:00,2016/7/3,18,1000.5,1005.4,330.0,0.7,25.7,98.0,0.4
2016-07-03 21:00:00,2016/7/3,21,1000.4,1005.3,999017.0,0.0,25.7,98.0,0.0
2016-07-04 00:00:00,2016/7/4,0,1000.6,1005.5,176.0,2.0,26.3,97.0,0.0
2016-07-04 03:00:00,2016/7/4,3,1000.5,1005.3,179.0,2.1,31.8,69.0,0.0
2016-07-04 06:00:00,2016/7/4,6,999.7,1004.5,160.0,1.7,34.7,56.0,0.0
2016-07-04 09:00:00,2016/7/4,9,998.8,1003.6,287.0,1.4,34.8,55.0,0.0
2016-07-04 12:00:00,2016/7/4,12,1001.1,1006.0,340.0,1.0,29.7,78.0,0.0
2016-07-04 15:00:00,2016/7/4,15,1001.1,1005.9,188.0,1.3,27.8,79.0,0.0
...,...,...,...,...,...,...,...,...,...
2016-10-14 06:00:00,2016/10/14,6,1015.8,1020.9,359.0,1.9,18.5,84.0,0.0
2016-10-14 09:00:00,2016/10/14,9,1015.5,1020.6,349.0,2.0,18.2,81.0,0.0
2016-10-14 12:00:00,2016/10/14,12,1016.5,1021.6,1.0,1.4,18.3,83.0,0.0
2016-10-14 15:00:00,2016/10/14,15,1015.9,1021.0,354.0,1.8,18.2,87.0,0.0
2016-10-14 18:00:00,2016/10/14,18,1015.4,1020.5,202.0,1.1,18.4,89.0,0.0
2016-10-14 21:00:00,2016/10/14,21,1015.2,1020.3,360.0,2.3,18.5,90.0,0.0
2016-10-15 00:00:00,2016/10/15,0,1016.5,1021.6,35.0,2.0,19.0,95.0,0.0
2016-10-15 03:00:00,2016/10/15,3,1015.8,1020.9,357.0,1.1,19.8,94.0,0.6
2016-10-15 06:00:00,2016/10/15,6,1013.7,1018.8,334.0,1.5,20.3,96.0,0.1
2016-10-15 09:00:00,2016/10/15,9,1013.7,1018.8,333.0,2.2,20.3,96.0,0.0
2016-10-15 12:00:00,2016/10/15,12,1014.5,1019.6,344.0,0.9,20.0,97.0,0.0
2016-10-15 15:00:00,2016/10/15,15,1013.9,1019.0,999017.0,0.0,19.8,97.0,0.0
2016-10-15 18:00:00,2016/10/15,18,1012.9,1017.9,215.0,1.7,19.7,97.0,0.0
2016-10-15 21:00:00,2016/10/15,21,1012.8,1017.8,216.0,3.2,19.6,97.0,0.0
2016-10-16 00:00:00,2016/10/16,0,1013.9,1018.9,327.0,0.6,20.4,95.0,0.0
2016-10-16 03:00:00,2016/10/16,3,1013.9,1018.9,342.0,2.2,24.6,76.0,0.0
2016-10-16 06:00:00,2016/10/16,6,1011.7,1016.7,301.0,1.8,26.8,67.0,0.0
2016-10-16 09:00:00,2016/10/16,9,1011.7,1016.7,10.0,4.1,24.9,74.0,0.0
2016-10-16 12:00:00,2016/10/16,12,1013.8,1018.8,353.0,4.3,22.7,77.0,0.0
2016-10-16 15:00:00,2016/10/16,15,1014.7,1019.7,7.0,2.1,21.9,80.0,0.0
2016-10-16 18:00:00,2016/10/16,18,1014.5,1019.5,344.0,2.0,21.3,83.0,0.0
2016-10-16 21:00:00,2016/10/16,21,1014.2,1019.2,35.0,3.0,20.4,81.0,0.0
2016-10-17 00:00:00,2016/10/17,0,1015.6,1020.6,35.0,2.1,20.1,80.0,0.0
2016-10-17 03:00:00,2016/10/17,3,1015.6,1020.6,104.0,1.5,19.6,90.0,0.1
2016-10-17 06:00:00,2016/10/17,6,1013.4,1018.4,81.0,1.2,21.3,79.0,0.0
2016-10-17 09:00:00,2016/10/17,9,1013.7,1018.7,109.0,1.1,20.9,79.0,0.0
2016-10-17 12:00:00,2016/10/17,12,1014.3,1019.4,17.0,0.7,19.6,87.0,0.0
2016-10-17 15:00:00,2016/10/17,15,1014.7,1019.8,222.0,0.9,18.9,92.0,0.0
2016-10-17 18:00:00,2016/10/17,18,1014.0,1019.0,341.0,1.5,19.1,92.0,0.0
2016-10-17 21:00:00,2016/10/17,21,1013.9,1018.9,322.0,2.5,19.3,90.0,0.0

In [139]:
#weather_raw_data11.date.apply(lambda x :'{}'.format(x)) + weather_raw_data11.hour.apply(lambda x :'{:02}'.format(x))
list(weather_raw_data11['wind_direction'].values).count(999017)

8

In [113]:
aaa = range(1,4)